
language: node_js

node_js:
  - 0.10
  - 0.11
  - 0.12
  - 4
  - 6
  - 8
  - 10
  - 11
  - 12
  - node

after_success:
  - npm run cover

matrix:
  allow_failures:
    node_js:
      - 0.10
      - 0.11
      - 0.12
      - 4
  
